from dataclasses import dataclass, field
from typing import Tuple, List, Optional, TypedDict, Callable, Any
import time
import copy

class RawDetection(TypedDict):
    """Output from the DetectorBackend (e.g., YOLO inference)."""
    class_name: str
    confidence: float
    bbox: Tuple[int, int, int, int]
    center: Tuple[int, int]
    # Exact detected outline in absolute frame pixel coordinates (e.g. the 3
    # or 6 vertices HSVContourDetectorBackend's cv2.approxPolyDP already
    # finds), so the dashboard can trace the real shape instead of a generic
    # axis-aligned box. Optional: None for backends (e.g. YOLO) that only
    # produce a bbox, in which case the dashboard falls back to the box.
    polygon: Optional[List[Tuple[int, int]]]

class TrackedDetection(TypedDict):
    """Output from the TrackerBackend (e.g., ByteTrack)."""
    class_name: str
    confidence: float
    bbox: Tuple[int, int, int, int]
    center: Tuple[int, int]
    tracking_id: int
    polygon: Optional[List[Tuple[int, int]]]
class TargetData(TypedDict):
    """Standardized output from the TargetSelector."""
    target_key: str  # e.g., 'blue_hexagon'
    name: str        # e.g., 'hexagon'
    color: str       # e.g., 'blue'
    confidence: float
    center: Tuple[int, int]
    bounding_box: Tuple[int, int, int, int]
    polygon: Optional[List[Tuple[int, int]]]
    tracking_id: int
    is_locked: bool
    distance_from_center: float
    pixel_error: Tuple[float, float]
    is_stale: bool
    timestamp: float

@dataclass
class FlightIntent:
    """Represents the desired action of the UAV generated by the MissionManager."""
    mode: str = "HOVER"  # "HOVER", "VELOCITY_BODY", "NAVIGATE_NED", "GOTO_NED",
                         # "ARM_OFFBOARD", "OFFBOARD_STOP", "DISARM", "KILL", "IDLE"
    velocity: Tuple[float, float, float] = (0.0, 0.0, 0.0)  # v_fwd, v_right, v_down
    target_ned: Optional[Tuple[float, float, float]] = None
    target_heading: Optional[float] = None  # Desired yaw angle in degrees
    yaw_rate: float = 0.0

@dataclass
class Event:
    """Represents an asynchronous state transition trigger."""
    name: str
    source: str
    timestamp: float = field(default_factory=time.time)
    payload: dict = field(default_factory=dict)

@dataclass
class MissionStateData:
    """Shared state representation of the MissionManager."""
    current_state: str = "BOOT"
    previous_state: str = "NONE"
    state_entry_time: float = field(default_factory=time.time)
    active_mode: str = "IDLE"
    completed_targets: List[str] = field(default_factory=list)
    active_filter: List[str] = field(default_factory=list)
    current_decision: str = ""
    next_planned_action: str = ""
    search_progress: str = ""
    warnings: List[str] = field(default_factory=list)

    def state_time(self) -> float:
        return time.time() - self.state_entry_time

@dataclass(frozen=True)
class UISnapshot:
    """Immutable snapshot generated by main loop for the UI."""
    timestamp: float
    frame_id: int

    # Vision
    frame_bgr: Any  # np.ndarray, but we avoid importing numpy in types if possible, or just Any
    target_data: Optional[TargetData]
    active_filter: List[str]
    vision_fps: float
    detector_fps: float
    tracker_fps: float
    pipeline_latency: float

    # Mission
    mission_state: str
    mission_phase: str
    mission_time: float
    completed_targets: List[str]
    pickup_target: str
    payload_status: str

    # Flight
    flight_mode: str
    is_armed: bool
    alt_rel: float
    # None until MavController.ned_ready -- the position_velocity_ned stream
    # hasn't delivered its first real sample yet (see main.py). Every
    # consumer of this field must handle None, not assume a tuple.
    ned: Optional[Tuple[float, float, float]]
    velocity: Tuple[float, float, float]
    yaw_deg: float

    # Servo
    flight_intent: str
    descent_gate: float
    aligned_frames: int

    # Diagnostics & Additions
    recent_events: List[Event]
    dropped_snapshot_count: int
    safety_banner: str
    is_logging: bool
    ui_latency_ms: float

    # Mission Map reference points (local NED), for the dashboard's MISSION
    # MAP panel. None until MissionMemory actually records them.
    start_ned: Optional[Tuple[float, float, float]] = None
    start_heading: Optional[float] = None
    drop1_ned: Optional[Tuple[float, float, float]] = None
    drop1_color: Optional[str] = None
    drop2_ned: Optional[Tuple[float, float, float]] = None
    drop2_color: Optional[str] = None

class EventBus:
    """Simple pub/sub system for global event broadcasting without coupling."""
    def __init__(self):
        self.subscribers: List[Callable[[Event], None]] = []

    def subscribe(self, callback: Callable[[Event], None]):
        self.subscribers.append(callback)

    def publish(self, event: Event):
        # Dispatch to all subscribers
        for sub in self.subscribers:
            try:
                sub(copy.deepcopy(event))
            except Exception as e:
                print(f"[EventBus] Error in subscriber: {e}")

# Global Event Bus instance
event_bus = EventBus()
